### ISSUE TITLE
Doxygen: empty index.html

### ISSUE THREAD

**Issue by szugyizs** [itsBelinda/ENG5220-2020-Team13#5]
Doxygen is not processing the source code file structure correctly, and generates an empty index file.
To be checked again in a desktop environment, as opposed to the Pi.

**Comment by itsBelinda** [comment]
How is it going with that? 
Do you need assistance?
IMO, it's more than enough if the Doxygen generation works on a desktop environment, but the generated files need to be included in the github

**Comment by szugyizs** [comment]
Resolved issue - works on desktop. Outputs can be found in the doc folder.
